apiVersion: ENC[AES256_GCM,data:GPc=,iv:ZhxUFVezbv11zBFc/mzA2L9JBWv/mRHlKQwa2OK77us=,tag:zXP86Kg05eSWH0SAf+fD/g==,type:str]
kind: ENC[AES256_GCM,data:Lp8oRteZ,iv:kfMLnrnFkELgjVZzUAoh2kiVcyOP82HNxJKmlWd6CP4=,tag:rhf6c4bsCV+UFUs+lIIUOw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:C/JjEzEHl4YTZzVHG24x,iv:VtPv1iNSmsa1I8Q5yxLz842nSq19QBhCBzI4ki9apE8=,tag:qewPquZvaVd/4xFZVeVFJg==,type:str]
    namespace: ENC[AES256_GCM,data:hZsfZG7Ldrgd1WF2FIFd,iv:TDsCXQ4PJ5pMrbGd3B/ZWcuZUFieWUAq7gw1vQ2GrF4=,tag:+2wKsc15aGta6NZhiycJqw==,type:str]
type: ENC[AES256_GCM,data:VwUD7mP2,iv:0V6fvVfdig0dor1PecUjtHLWNOLT5STMrGEV1mlUO00=,tag:clFlsydJHgEHDPLFBSJTBA==,type:str]
stringData:
    CRYPTO_KEY_VALUE: ENC[AES256_GCM,data:APwwSLS79QQQ9r05xl8bLqlkdRo+v2jeFxHV6uDUsGSPJxjneAtw0ukx6g+CSv+UYSNv/IsjPakzyWPYEIzOI3jc543PXrWL43E2srSTkeSK3WmAhZCsPu1WMUDGahsYfosRMg==,iv:pxlgEEG/Cx9SJecX929D5aa9a16D1ck/48YIus2p4vo=,tag:DNUDlEAHEQ2sL2BNIPmfeA==,type:str]
    CRYPTO_KEY_PROVIDER: ENC[AES256_GCM,data:++KdLsBX,iv:WDb0axgM/FwfEa883B9+McVZ2u61zFqbdlSAYakhRJE=,tag:rBKbFeQ0NG3OuCw5tFYw5Q==,type:str]
    CRYPTO_KEY_CIPHER: ENC[AES256_GCM,data:/aoZ9SsKVfrBu0c3inW2,iv:d8kTga6DPwPz8QvXJknGp2yuGhoa5GB+s7KpnM0eJY8=,tag:pjDx5spIGBzw5qekybao1Q==,type:str]
    CRYPTO_KEY_HASH: ENC[AES256_GCM,data:X8mOHsuo,iv:7mtqsUr6UBkqZmOvQ1gq0p5fsdBDkXkHfKHeXmOwITE=,tag:Mz42kPP9uz1Q8TqrfOs2NA==,type:str]
    CRYPTO_KEY_SIZE: ENC[AES256_GCM,data:GbDf,iv:K4UzLaj0taGvB3k9VkAVgWW4NSNXZlaDfFK67NFJkC0=,tag:SptBRJFkjCEHHOjDKTfTTA==,type:str]
    CRYPTO_PBKDF: ENC[AES256_GCM,data:G7+guxqzqg==,iv:AAveDAsoESOkyJM4RrxmSifksTQNBp0fIY5d6LS6R7Y=,tag:2PaQ4ouCUw10+jw39XsLjQ==,type:str]
sops:
    age:
        - recipient: age1jxtdxm70ltr637yy5c00586r9q5mfx8ldgw8r5ye2cehpncygupsmjxjwh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2QStlZU04V055V2ZXMk5l
            NkZ5MkM2VEdMaWdWVWMrN1ZiUzB0T2o0QlRNCnFFQTlVZjhCZ1dMYnJ0SkxMVXMy
            ZHdTYlpQRml1SW1xbHRONTJMVWEwdFEKLS0tIHpaKzBjWFp0cEladWM5RVVJbWhx
            d3BYd05NNk5ZZWdkUVdUaGJpc01lWVUKFbWxO6b8mYXzlgcV0Zg6iLv99FmO0BXG
            vCLYCE6cs6mahYf//GZAZIt15EpBoM+6Zbv6+t0IyOcnoUSK3v7QQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T04:17:56Z"
    mac: ENC[AES256_GCM,data:E0uX1Ye5vtVc729LQMo2JOdC5xu2P2lnzeEVjeDBQfvqWt2vjdRuuSH2oXf6gOParNtWIV5ap+Y4azdMRmUEDFj5exJ2R9jaO04G5vMvjxghfYs+9wN40xLIAFFWRmiVLbCxFeye922+2Tdb5emOje1NfNN7pCF6iEsnpdx5nCk=,iv:OEhPtAODBZGtinWIoqhFGydvM9LfyGzCtVLf+jmixVg=,tag:Dl3GmvDMo37D82/qgouBWA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
