---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-data-encrypted
  namespace: factorio
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-encrypted
  resources:
    requests:
      storage: 10Gi

