apiVersion: ENC[AES256_GCM,data:fmQ=,iv:GtUiXRh7sBcjan9+TN4Ye6P8xlLXDQ3yZo0k2EWAICY=,tag:LX/AB6Jjqyy6KzuREoIglg==,type:str]
kind: ENC[AES256_GCM,data:z17p0G35,iv:rqTXVafNSSbSuDFizzMH5Lv3b/fUl4yVIk1lzno+IoU=,tag:1wNpFwhDDsIKKv1MCG4m5Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:CSOgIrKdwIE4rQWdVw==,iv:CFqFQUHiK2nfiVD6tkQAxHJjOblIVF/pbFNq9PhFtls=,tag:VXdmng3ptGwmOZ6bbGp2+Q==,type:str]
    namespace: ENC[AES256_GCM,data:pq4hDJnk9Z0=,iv:WFW2q7+9Zvkviwn8yl5EOs4UQ9lwFZCFnsRhwkN4B2E=,tag:+p68SgLMwVgHywt7x28HFw==,type:str]
type: ENC[AES256_GCM,data:RBc8pMu9,iv:oFRb/p/p5s+kWR4NfqlolMaD37l5OM9NYJ0XEQERD3o=,tag:iFuLPbU3uhnk7o6xfPK+uQ==,type:str]
stringData:
    secret-key: ENC[AES256_GCM,data:e1rlmtDznLSdJQF54AFsEle46D6XHgO+6PjyYuhr+QM2bdwK8538ZGino/cEabm9RerGnmyW3RA8Wsmph45R9g==,iv:gr5GqYqdxhrQPM71/RNS/URaekV89/JwTN5AnsRKuqM=,tag:sE5Di9xheoQTxHzG2ck1rQ==,type:str]
sops:
    age:
        - recipient: age1jxtdxm70ltr637yy5c00586r9q5mfx8ldgw8r5ye2cehpncygupsmjxjwh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKaWpFZEt1bjB0ZDc2RXVX
            Y1h5eWVoakZBdDd5aThSb0VLSzFVeFlxQjBzCjR4RHlBRDloV2RiRXZ5ZkRYbTZZ
            Mk51Nis5cWQ4UEdqbTlNcGxreEdNNTQKLS0tIGFHek5yWkloVFlZdWNSYUJYUUI5
            TzNJbTRTMmdaUW5qWXUxZ0tlUVdsNjAKjiTYwSWEQOK9cMTVs0EjNnOwmxUw2OLh
            3hMmYgtPgSDT5SThUv3JHElVhlo7ICGq3BBIk+BAfVz6mT/4H28Q7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T00:54:29Z"
    mac: ENC[AES256_GCM,data:mkz2YUN0PLT0Uz0av7GEBkJOP9cK1vUWHmGopfOTQsq2yXs2COLpKW+dMx0PV2xzD5p2Y/TWs8ffyM4iOlD4/LuxgI3XvjzFrYLELv+f+zrLGnqOAcxYOpUEMzvI69mKUOwzxRnnNtARLFtsZ0sQFjZyGOIriVghyMBChafKR64=,iv:HfH3l+lsOTnCly1b9ueelB2WPdC+mipR4QNBcgwMYVQ=,tag:HysPJzdikjFhWo5KnHULdA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
