---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data-encrypted
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-encrypted
  resources:
    requests:
      storage: 20Gi
