apiVersion: ENC[AES256_GCM,data:QsQ=,iv:aF8U1oClFsnvazOVaJJ8BHkb5z9xV9FL0ve6CpsJ5VA=,tag:uKNqTOZqK0Kk8944IExN0w==,type:str]
kind: ENC[AES256_GCM,data:HbjFFE06,iv:VSa8qjKMlbK/FpZLZVu8gqPlh4qpc7x5EqK8kUm5tu4=,tag:Wharh6lT25qhlTSUqzAidA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:x846+S/gxd6zgQTqCw==,iv:vrC5yX7tW2f1FCtkU0q67LxfXxcBirc/LfhRq1cT3mM=,tag:2nYv8zjcEAvK+0kDqvAUPg==,type:str]
    namespace: ENC[AES256_GCM,data:9KrEk2oW6P/i,iv:gsNUlRXjvezCHtj3sZ7lBmnTkhZ2qdg66S3hSskXcAE=,tag:Zal/+njiYZlaCRNkGTUK0A==,type:str]
type: ENC[AES256_GCM,data:Fe6GCtub,iv:8upHwAR9nDzPFLgg2oVYCgn4B9aqHpD7DENTJVzDJqQ=,tag:7fsM0/jZo+chg8xqo9qt2Q==,type:str]
stringData:
    secret-key: ENC[AES256_GCM,data:KGKY4mArwkYbyy6VjVjTLXH9nypF+ab6AA4dRsTCyjpFtNYPxsVuCe53fzdrjm/UH6n/iko1JT2S0mRI3quxDQ==,iv:8AWLw0UheyK4vPR6w9Lm1u97bAKlVMtFzbmvtlbQGxc=,tag:+lvtEh7l/jqEspBfJIcJCw==,type:str]
sops:
    age:
        - recipient: age1jxtdxm70ltr637yy5c00586r9q5mfx8ldgw8r5ye2cehpncygupsmjxjwh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlQVlMd0tLNkZBWHMrTDkx
            cFp2TUNzdVBwODFHeVl1ZngxbzR6VUl5OW1JCmhyNXN1M21zc0VPdVdRcmFxZHJy
            Qjh3SzFYYmFZUWFQVFQzTkRKOG5tUnMKLS0tIGplY0NRT3ZreG1zbzBXYW41THBH
            U21rV1RJQjQ2N0haU3A2a2tOVzdJWmMKYz7MfRNTkiN2d0c2Y3AQEmIp8KESRE0v
            lExPPJ/c0SN5UtpgnTwWaKcvUhPr5JGaOgc0+UJmRO0FXPRCKDZ+mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T03:09:26Z"
    mac: ENC[AES256_GCM,data:Pp4E/RLzcZR3P6bjHaFzsgfx3I+xgROOVMhiR6zliu0b9KoQPQdHc3Da5nB0tWKKxkgW/WlgdyFciy9LUxYRRTau+q6LPPyavMMc6/wh8IGC5v90r5I7fsWrUPKQdAOFT+o2XKR4AV0e+Zh5+jvwcpE2ih+zI++3TYfLDs3Lq5s=,iv:pXdEojrYgsRng2QGdXJjDwC/8TOHwE/xmSQoY9WftC0=,tag:vcfiCn0NPpWYm0FQ3RFcqw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
