apiVersion: ENC[AES256_GCM,data:MEc=,iv:Sboli8XYpJ8UhYvirBNkebe1AD+//EdhQYGeWOkkdtg=,tag:bpF+xcro2V2uuhXPoJE2rg==,type:str]
kind: ENC[AES256_GCM,data:v1sJGu62,iv:b/RNirZg7I1ojWvKHAHO8xP6LrN2QC8AuLIs9L/70LQ=,tag:TxGLzi8OPvI7PVBIfo2Yqw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:U+4VztiUOKNvWDDv5WeQ,iv:gZa6cU1jylZm5Volid7fFfr6Y7VVNMiYxTDm2nfM+/s=,tag:f50e/epv+ipFxHrv2NNIjQ==,type:str]
    namespace: ENC[AES256_GCM,data:/vih5rzBe2zq,iv:QjP9kB88KyYWtaWSJpR3+Dmtukuh6xb2WFemkoTzlzs=,tag:TYZC64mohlhpSbjnUEe9KQ==,type:str]
type: ENC[AES256_GCM,data:dNm89JWe,iv:JW5Vo5NP1Qooo3W0LsNDwZWZSUK4Hg86POX/dIFKfr8=,tag:oQ1l/9qTS4lxXi+tRnExwA==,type:str]
stringData:
    clientId: ENC[AES256_GCM,data:yhQvM9UGcviKDx/yGsnhluA=,iv:N3GXdTgQjtI5ceMfmeE0yi2z9gDbJcQkiDc6R2rtiEs=,tag:hVEyzkNiocpMnfyJg/ltbg==,type:str]
    clientSecret: ENC[AES256_GCM,data:w+mC/CciyPimU41Dg/gb/diR6p+M9cKbAu3Jd1Q9A0M3gVrWciWgdE0j9jtAgGAVgg6bSk4u0jzLjPm8eoUs9g==,iv:QJf9qCy1Jz+XJrQeLJtp7IM7dBf4bhDOFvXcRPRO88E=,tag:GBxMoFl9Iqsx+hC9ypg93Q==,type:str]
sops:
    age:
        - recipient: age1jxtdxm70ltr637yy5c00586r9q5mfx8ldgw8r5ye2cehpncygupsmjxjwh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZDRPUzA3SVlmeDNnYUk5
            ZHZBVGh1OXI5aWxCT0dWWEFSdTRhd0tLT0djCktiU0VZUi9aSUJhOE5zeXR1TTdH
            bFVFY2ZNVGF2R3V1T1NCaDZpaHdhbFEKLS0tIDJHeEMvVzYrSjRhbHFWN09aK0xX
            OXBvSGFDZXBSQzRyalE4ZTRxLzU5Z1kKI+y0VB9Y64+8/WjefejiiAZmV9U+d5Ni
            QZvHlcwNnvy/Ruk7DKDN3R2Jcp5pr/rmlaS9x3Yz7CH0uJRIzQa7DA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-18T04:02:13Z"
    mac: ENC[AES256_GCM,data:S2KfS9LnhLSerYSfW1ySpI7w+Ko1S7Ab+gY2kEWvDnILYMNHdS6HsMhXzqZ5fBSPinUBuTBOGHOkMPzACar6x0tdB41oRlT5t0W7RT0Nw2ZGgPFpe1zFOrjKFiEnZycQP9Hz04v/9V9o7O/Iez10DFPYPfT0mni1eTBiyetBp4g=,iv:vfKsk0lOozKFqfvSKyhLDiELuIUfn4RPyKJhlT5+1ok=,tag:uhYxkEcl+3+rtEUKj/Y18g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
