apiVersion: ENC[AES256_GCM,data:oQQ=,iv:+V0K8a2T/Q+zVHrwP8z4ibP+kDz2CiaBIJbiBibBd0Q=,tag:F+ZG0Y0dM3emvP6RoEzG+g==,type:str]
kind: ENC[AES256_GCM,data:6pN26h2U,iv:+Et76O6HrL7qnhStVTBL9XDJRhYBJvli3J1mF4kJtac=,tag:CXL2Zf3l4YuJEgwQeQxtJQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:XwOSIE0gcB6e0w==,iv:bVeCia4sdktvRuua6KDSd0nxHFKvc3C6cpUMkzs0Rjc=,tag:v5sJPVW7QSM3dAzqeaI+LA==,type:str]
    namespace: ENC[AES256_GCM,data:eVURAg==,iv:PNTA2vK1Q75Xdt6jdGRzFY3mWVqNh44+ZBgTujS+MeU=,tag:RSQMuWtkoiA96PvFIfIGxQ==,type:str]
type: ENC[AES256_GCM,data:MUSdGlXi,iv:8i5oQqRObscNg+u24DbISBZU4W/rE0pNR5SgfFDC0l4=,tag:RemrqIY/gS3cxRMm/O7k/w==,type:str]
stringData:
    claim: ENC[AES256_GCM,data:ff+8iz75Jhs6/75DwJkhmTKk/maYc5Nd9vY=,iv:qElRNL02TC2LOxkd/lz7QcY4xsa/0Q6fQIgdCLu80Cs=,tag:SLUAGQkASprYpNYV6J4wdg==,type:str]
sops:
    age:
        - recipient: age1jxtdxm70ltr637yy5c00586r9q5mfx8ldgw8r5ye2cehpncygupsmjxjwh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TFNTQU9McDZxQUtuZ1BB
            Smt1Q2RoSEZrQnYvMU1yL1lBSXN1VFc4dTN3CnFVbXJpbVBmTWFQZVpjMjhBUDFv
            UDV4T0JSQzJJM3QzSUEzT0lxdXAvaGsKLS0tIHBxVjJHSmJFeG56QW4zeDdsTVZt
            cXJsbHNrYXFqeEpkbUNDdUpBa1haRkEK5+mdO5TJRInSA9CbhhELDIJmiYcljY1R
            0A/0832uPZe2xZ6YYy+/A6u8cwQFG1F5tRJsKUD3IyIzU0E+Cith2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T00:56:39Z"
    mac: ENC[AES256_GCM,data:Q4ilO0WaEH+0YCs0oHx7fN/HMuIs2xNhqBdXUZ8bmOtV7BQP1WnYkKsO8d2/zbtETK18DQEC0/Cm0+sLiCef7QUib3Zzen/FDXQxZUgjGjKYTms4Hsa9PuCPX+PgBOqqKnp5Jk4IhJgzU1+sT3pqw/2ul/11v4nZFk4+B+BtsLw=,iv:upyX8nBIH+IRdy7R7Gp7jCdYqFvGHxGysOGbtif9viA=,tag:nnXq4Ou9gHqLP14V+WO6wA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
